# Generated by Django 5.2 on 2025-04-29 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_recurringtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=5)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'currencies',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_base',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='budget.currency'),
        ),
    ]
