# Generated by Django 5.2 on 2025-04-29 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_currency_transaction_amount_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='budget.currency'),
        ),
    ]
