# Generated by Django 5.2 on 2025-04-29 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_recurringtransaction_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='budget.currency'),
            preserve_default=False,
        ),
    ]
