# Generated by Django 5.2 on 2025-05-01 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_budget_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount_base',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.currency'),
        ),
    ]
